apiVersion: v1
kind: Service
metadata:
  name: {{ include "techmart.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "techmart.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
