apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: techmart
resources:
  - techmart-namespace.yaml
  - techmart-config.yaml
  - techmart-secret.yaml
  - postgres-deployment.yaml
  - techmart-deployment.yaml
  - frontend-deployment.yaml
  - techmart-ingress.yaml
